Repository OCA/storage, pull requests merged in 2020-06, with the labels that each got.

#44 [12.0] storage_file: fix error creating a new file
  storage_file/models/storage_file.py
  storage_file/tests/test_storage_file.py
Labels: approved, bot is merging ⏳, ready to merge

#39 storage_file: improve `_get_backend_id_from_param`
  storage_file/models/storage_backend.py
Labels: bot is merging ⏳, needs review

#41 [12.0][IMP] storage_image - add some fields in the views
  storage_image/views/storage_image_view.xml
Labels: bot is merging ⏳

#17 [10.0] sftp tests + OCA's pre-commit
  .eslintrc
  .flake8
  .isort.cfg
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  storage_backend/__manifest__.py
  storage_backend/components/base_adapter.py
  storage_backend/components/filesystem_adapter.py
  storage_backend/models/keychain.py
  storage_backend/models/storage_backend.py
  storage_backend/tests/common.py
  storage_backend_s3/__manifest__.py
  storage_backend_s3/models/storage_backend.py
  storage_backend_s3/tests/test_amazon_s3.py
  storage_backend_sftp/README.rst
  storage_backend_sftp/__manifest__.py
  storage_backend_sftp/components/sftp_adapter.py
  storage_backend_sftp/tests/test_sftp.py
  storage_file/__manifest__.py
  storage_file/controllers/main.py
  storage_file/models/storage_file.py
  storage_file/tests/test_storage_file.py
  storage_image/__manifest__.py
  storage_image/models/storage_image.py
  storage_image/tests/test_storage_image.py
  storage_image_category_pos/__manifest__.py
  storage_image_product/__manifest__.py
  storage_image_product/migrations/10.0.2.0.0/pre-migration.py
  storage_image_product/models/category_image_relation.py
  storage_image_product/models/product_category.py
  storage_image_product/models/product_image_relation.py
  storage_image_product/models/product_product.py
  storage_image_product/tests/common.py
  storage_image_product/tests/test_product_image_relation.py
  storage_image_product_pos/__manifest__.py
  storage_media/__manifest__.py
  storage_media/models/storage_media.py
  storage_media_product/__manifest__.py
  storage_media_product/models/product.py
  storage_thumbnail/__manifest__.py
  storage_thumbnail/models/storage_thumbnail.py
Labels: needs review

#54 [FIX] fix travis, temporary inactive test on V10 for amazon S3
  .travis.yml
Labels: bot is merging ⏳

#28 [10.0] storage_image_product: avoid "replace" in view inheritance
  storage_image_product/views/product_product.xml
  storage_image_product/views/product_template.xml
Labels: approved, bot is merging ⏳

#42 [12.0][IMP] storage_image_product improve view
  storage_image/readme/DESCRIPTION.rst
  storage_image/views/storage_image_view.xml
  storage_image_product/__manifest__.py
  storage_image_product/models/__init__.py
  storage_image_product/models/storage_image.py
  storage_image_product/views/storage_image.xml
Labels: bot is merging ⏳

#37 [MIG] storage_backend_sftp: Migration to 13.0
  storage_backend_sftp/__manifest__.py
  storage_backend_sftp/models/storage_backend.py
  storage_backend_sftp/tests/test_sftp.py
Labels: bot is merging ⏳, needs review
