Repository OCA/storage, pull requests merged in 2020-11, with the labels that each got.

#48 [12.0][ADD] Storage image product: Image handle widget
  storage_image/models/__init__.py
  storage_image/models/image_relation_abstract.py
  storage_image/readme/CONTRIBUTORS.rst
  storage_image/static/src/css/image_handle.css
  storage_image/static/src/js/image_handle.js
  storage_image/views/js.xml
  storage_image_product/models/category_image_relation.py
  storage_image_product/models/product_image_relation.py
  storage_image_product/views/product_category.xml
  storage_image_product/views/product_image_relation.xml
  storage_image_product/views/product_product.xml
  storage_image_product/views/product_template.xml
Labels: approved, bot is merging ⏳, ready to merge

#56 [10.0][ADD] Storage image product: Image handle widget
  storage_image/README.rst
  storage_image/__manifest__.py
  storage_image/models/__init__.py
  storage_image/models/image_relation_abstract.py
  storage_image/static/src/css/image_handle.css
  storage_image/static/src/js/image_handle.js
  storage_image/views/js.xml
  storage_image_product/README.rst
  storage_image_product/models/category_image_relation.py
  storage_image_product/models/product_image_relation.py
  storage_image_product/views/product_image_relation.xml
  storage_image_product/views/product_product.xml
  storage_image_product/views/product_template.xml
Labels: bot is merging ⏳

#65 [12.0][FIX] storage_image: Indefinite error
  storage_image/static/src/js/storage_image.js
Labels: approved, bot is merging ⏳, ready to merge

#70 [FIX] fix wrong key in manisfest'
  storage_backend/__manifest__.py
  storage_file/__manifest__.py
  storage_image/__manifest__.py
  storage_image_product/__manifest__.py
  storage_thumbnail/__manifest__.py
Labels: bot is merging ⏳

#55 [13.0][ADD] Image handle widget
  storage_image/models/__init__.py
  storage_image/models/storage_relation_abstract.py
  storage_image/readme/CONTRIBUTORS.rst
  storage_image/static/src/css/image_handle.css
  storage_image/static/src/js/image_handle.js
  storage_image/views/js.xml
  storage_image_product/models/category_image_relation.py
  storage_image_product/models/product_image_relation.py
  storage_image_product/readme/CONTRIBUTORS.rst
  storage_image_product/views/product_category.xml
  storage_image_product/views/product_image_relation.xml
  storage_image_product/views/product_product.xml
  storage_image_product/views/product_template.xml
Labels: bot is merging ⏳

#69 [13.0][PORT] 65 from 12.0
  storage_image/static/src/js/storage_image.js
Labels: bot is merging ⏳, needs review

#68 [13.0] Add move_files / find_files features
  storage_backend/__manifest__.py
  storage_backend/components/base_adapter.py
  storage_backend/models/storage_backend.py
  storage_backend/tests/common.py
  storage_backend/tests/test_filesystem.py
  storage_backend_s3/__manifest__.py
  storage_backend_s3/tests/test_amazon_s3.py
  storage_backend_sftp/__manifest__.py
  storage_backend_sftp/components/sftp_adapter.py
  storage_backend_sftp/tests/test_sftp.py
Labels: approved, bot is merging ⏳, ready to merge

#71 [13.0][PORT] 44 from 12.0
  storage_file/models/storage_file.py
  storage_file/tests/test_storage_file.py
Labels: bot is merging ⏳

#72 [13.0][PORT] 38 from 12.0
  storage_image/__manifest__.py
Labels: bot is merging ⏳

#75 Implement public API
  storage_backend/models/storage_backend.py
  storage_backend/tests/common.py
  storage_backend/tests/test_filesystem.py
  storage_backend_sftp/tests/test_sftp.py
  storage_file/models/storage_file.py
  storage_file/tests/test_storage_file.py
Labels: approved, bot is merging ⏳
