Repository OCA/storage, pull requests merged in 2021-02, with the labels that each got.

#90 [13.0] Sync with OCA/oca-addons-repo-template
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .gitignore
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  CONTRIBUTING.md
  LICENSE
  README.md
  oca_dependencies.txt
  storage_backend/__manifest__.py
  storage_backend_s3/__manifest__.py
  storage_backend_sftp/components/sftp_adapter.py
  storage_backend_sftp/models/storage_backend.py
  storage_backend_sftp/tests/test_sftp.py
  storage_backend_sftp/views/backend_storage_view.xml
  storage_file/__manifest__.py
  storage_image/__manifest__.py
  storage_image_category_pos/__manifest__.py
  storage_image_product/__manifest__.py
  storage_image_product_brand/__manifest__.py
  storage_image_product_pos/__manifest__.py
  storage_media/__manifest__.py
  storage_media/data/ir_parameter.xml
  storage_media/models/storage_media.py
  storage_media/security/ir_rule.xml
  storage_media/security/res_group.xml
  storage_media/views/storage_media_view.xml
  storage_media_product/__manifest__.py
  storage_media_product/models/product.py
  storage_media_product/views/product.xml
  storage_media_product/views/product_category.xml
  storage_thumbnail/__manifest__.py
  test-requirements.txt
Labels: bot is merging ⏳

#87 storage_s3: fix aws regions -> load once
  storage_backend_s3/models/storage_backend.py
Labels: approved, bot is merging ⏳, bug

#86 [FIX] storage_media_product: domain for media attributes
  storage_media_product/views/product.xml
Labels: approved, bot is merging ⏳, ready to merge

#88 storage_file: boost url compute
  storage_file/models/__init__.py
  storage_file/models/ir_actions_report.py
  storage_file/models/storage_backend.py
  storage_file/models/storage_file.py
  storage_file/tests/test_storage_file.py
Labels: approved, bot is merging ⏳, ready to merge
