Repository OCA/storage, pull requests merged in 2021-10, with the labels that each got.

#114 [14.0][IMP] add tag support for brand image
  storage_image_product_brand/models/__init__.py
  storage_image_product_brand/models/image_tag.py
  storage_image_product_brand/models/product_brand_image_relation.py
  storage_image_product_brand/views/product_brand_image_relation.xml
Labels: bot is merging ⏳

#124 [14.0] storage_thumbnail: refactor to ease override
  storage_thumbnail/models/thumbnail_mixin.py
Labels: bot is merging ⏳

#118 [14.0][FIX] storage media listed on product variant
  storage_media_product/models/product.py
Labels: approved, bot is merging ⏳

#126 [14.0][FIX] function _compute_main_thumbs
  storage_thumbnail/models/thumbnail_mixin.py
Labels: bot is merging ⏳

#127 [14.0][PORT] 101 from 13.0
  storage_media/security/ir_rule.xml
Labels: bot is merging ⏳

#101 [13.0][FIX] storage_media: Explicit ir rule definition for Storage File for Media
  storage_media/security/ir_rule.xml
Labels: approved, ready to merge, bot is merging ⏳

#121 [13.0][IMP] storage_image: Ensure variant image recomputation
  storage_image_product/models/product_product.py
Labels: bot is merging ⏳

#128 [14.0][PORT] 121 from 13.0
  storage_image_product/models/product_product.py
Labels: bot is merging ⏳

#130 [IMP] use notebook for a better UI
  storage_image_product_brand/views/product_brand.xml
Labels: approved, bot is merging ⏳

#113 [13.0][ADD] storage_import_image_advanced
  .travis.yml
  requirements.txt
  setup/storage_import_image_advanced/odoo/addons/storage_import_image_advanced
  setup/storage_import_image_advanced/setup.py
  storage_import_image_advanced/README.rst
  storage_import_image_advanced/__init__.py
  storage_import_image_advanced/__manifest__.py
  storage_import_image_advanced/data/ir_cron.xml
  storage_import_image_advanced/data/queue_job_channel_data.xml
  storage_import_image_advanced/data/queue_job_function_data.xml
  storage_import_image_advanced/i18n/shopinvader_import_image.pot
  storage_import_image_advanced/models/__init__.py
  storage_import_image_advanced/models/import_image.py
  storage_import_image_advanced/readme/CONTRIBUTORS.rst
  storage_import_image_advanced/readme/DESCRIPTION.rst
  storage_import_image_advanced/security/ir_model_access.xml
  storage_import_image_advanced/static/description/index.html
  storage_import_image_advanced/tests/__init__.py
  storage_import_image_advanced/tests/fixture/A001.jpg
  storage_import_image_advanced/tests/fixture/A002.jpg
  storage_import_image_advanced/tests/fixture/A003.jpg
  storage_import_image_advanced/tests/fixture/image_import_test.csv
  storage_import_image_advanced/tests/fixture/image_import_test.zip
  storage_import_image_advanced/tests/test_import_image.py
  storage_import_image_advanced/views/import_product_image_view.xml
  storage_import_image_advanced/views/report_html.xml
Labels: approved, bot is merging ⏳

#137 [FIX] 14.0 storage_image_product_pos: Only load assets in pos
  storage_image_product_pos/views/pos_product.xml
Labels: bot is merging ⏳
