Repository OCA/storage, pull requests merged in 2022-01, with the labels that each got.

#153 [13.0] [IMP] storage_backend_ftp
  storage_backend_ftp/components/ftp_adapter.py
Labels: approved, bot is merging ⏳

#158 [13.0][IMP] storage_image_product: display attribute_value_ids using many2many_tags widget
  storage_image_product/views/storage_image.xml
Labels: approved, ready to merge, bot is merging ⏳

#159 [14.0][IMP] storage_image_product: display attribute_value_ids using many2many_tags widget
  storage_image_product/views/storage_image.xml
Labels: bot is merging ⏳

#165 [14.0][IMP] storage_backend_ftp: Fix connection issue for implicit FTP over TLS
  storage_backend_ftp/components/ftp_adapter.py
Labels: approved, bot is merging ⏳
