Repository OCA/storage, pull requests merged in 2022-03, with the labels that each got.

#170 [14.0][FIX] storage_file: lock backends when refreshing base url on startup
  storage_file/models/storage_backend.py
Labels: approved, bot is merging ⏳

#177 [15.0][UPD] copier update
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  README.md
Labels: approved

#166 [15.0][MIG] storage_backend_ftp
  requirements.txt
  setup/storage_backend_ftp/odoo/addons/storage_backend_ftp
  setup/storage_backend_ftp/setup.py
  storage_backend_ftp/README.rst
  storage_backend_ftp/__init__.py
  storage_backend_ftp/__manifest__.py
  storage_backend_ftp/components/__init__.py
  storage_backend_ftp/components/ftp_adapter.py
  storage_backend_ftp/i18n/storage_backend_ftp.pot
  storage_backend_ftp/models/__init__.py
  storage_backend_ftp/models/storage_backend.py
  storage_backend_ftp/readme/CONTRIBUTORS.rst
  storage_backend_ftp/readme/DESCRIPTION.rst
  storage_backend_ftp/static/description/icon.png
  storage_backend_ftp/static/description/index.html
  storage_backend_ftp/tests/__init__.py
  storage_backend_ftp/tests/test_ftp.py
  storage_backend_ftp/views/backend_storage_view.xml
Labels: approved, ready to merge, bot is merging ⏳
