Repository OCA/storage, pull requests merged in 2022-10, with the labels that each got.

#188 [15.0][MIG] storage_file
  requirements.txt
  setup/storage_file/odoo/addons/storage_file
  setup/storage_file/setup.py
  storage_file/README.rst
  storage_file/__init__.py
  storage_file/__manifest__.py
  storage_file/controllers/__init__.py
  storage_file/controllers/main.py
  storage_file/data/ir_cron.xml
  storage_file/data/storage_backend.xml
  storage_file/i18n/storage_file.pot
  storage_file/models/__init__.py
  storage_file/models/ir_actions_report.py
  storage_file/models/storage_backend.py
  storage_file/models/storage_file.py
  storage_file/readme/CONTRIBUTORS.rst
  storage_file/readme/DESCRIPTION.rst
  storage_file/security/ir.model.access.csv
  storage_file/security/storage_file.xml
  storage_file/static/description/icon.png
  storage_file/tests/__init__.py
  storage_file/tests/test_storage_file.py
  storage_file/views/storage_backend_view.xml
  storage_file/views/storage_file_view.xml
Labels: approved, ready to merge

#189 [15.0] [MIG] storage_thumbnail
  setup/storage_thumbnail/odoo/addons/storage_thumbnail
  setup/storage_thumbnail/setup.py
  storage_thumbnail/README.rst
  storage_thumbnail/__init__.py
  storage_thumbnail/__manifest__.py
  storage_thumbnail/data/ir_parameter.xml
  storage_thumbnail/i18n/storage_thumbnail.pot
  storage_thumbnail/models/__init__.py
  storage_thumbnail/models/storage_file.py
  storage_thumbnail/models/storage_thumbnail.py
  storage_thumbnail/models/thumbnail_mixin.py
  storage_thumbnail/readme/CONTRIBUTORS.rst
  storage_thumbnail/readme/DESCRIPTION.rst
  storage_thumbnail/security/ir.model.access.csv
  storage_thumbnail/static/description/icon.png
  storage_thumbnail/static/description/index.html
  storage_thumbnail/tests/__init__.py
  storage_thumbnail/tests/models.py
  storage_thumbnail/tests/static/akretion-logo.png
  storage_thumbnail/tests/test_thumbnail.py
  storage_thumbnail/views/storage_thumbnail_view.xml
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#198 [14.0][IMP] storage_media_product: Add optional description
  storage_media_product/models/product.py
  storage_media_product/views/product.xml
Labels: approved, ready to merge, bot is merging ⏳

#190 [15.0][MIG] storage_image
  setup/storage_image/odoo/addons/storage_image
  setup/storage_image/setup.py
  storage_image/README.rst
  storage_image/__init__.py
  storage_image/__manifest__.py
  storage_image/data/ir_config_parameter.xml
  storage_image/i18n/storage_image.pot
  storage_image/models/__init__.py
  storage_image/models/storage_file.py
  storage_image/models/storage_image.py
  storage_image/models/storage_image_relation_abstract.py
  storage_image/readme/CONTRIBUTORS.rst
  storage_image/readme/DESCRIPTION.rst
  storage_image/security/ir.model.access.csv
  storage_image/security/ir_rule.xml
  storage_image/security/res_group.xml
  storage_image/static/description/icon.png
  storage_image/static/description/index.html
  storage_image/static/src/css/FieldStorageImageHandle.scss
  storage_image/static/src/js/FieldStorageImageHandle.js
  storage_image/tests/__init__.py
  storage_image/tests/common.py
  storage_image/tests/static/akretion-logo.png
  storage_image/tests/test_storage_image.py
  storage_image/views/storage_image.xml
  storage_image/views/storage_image_relation_abstract.xml
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#201 [15.0] [MIG] storage_backend_s3
  requirements.txt
  setup/storage_backend_s3/odoo/addons/storage_backend_s3
  setup/storage_backend_s3/setup.py
  storage_backend_s3/README.rst
  storage_backend_s3/__init__.py
  storage_backend_s3/__manifest__.py
  storage_backend_s3/components/__init__.py
  storage_backend_s3/components/s3_adapter.py
  storage_backend_s3/i18n/storage_backend_s3.pot
  storage_backend_s3/models/__init__.py
  storage_backend_s3/models/storage_backend.py
  storage_backend_s3/readme/CONTRIBUTORS.rst
  storage_backend_s3/readme/DESCRIPTION.rst
  storage_backend_s3/readme/ROADMAP.rst
  storage_backend_s3/static/description/icon.png
  storage_backend_s3/tests/__init__.py
  storage_backend_s3/tests/cassettes/AmazonS3Case.test_setting_and_getting_data_from_dir.yaml
  storage_backend_s3/tests/cassettes/AmazonS3Case.test_setting_and_getting_data_from_root.yaml
  storage_backend_s3/tests/test_amazon_s3.py
  storage_backend_s3/views/backend_storage_view.xml
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#218 [15.0][IMP] boto3 version bump
  requirements.txt
  storage_backend_s3/__manifest__.py
  storage_backend_s3/readme/ROADMAP.rst
  storage_backend_s3/static/description/index.html
Labels: approved, bot is merging ⏳
