Repository OCA/storage, pull requests merged in 2022-11, with the labels that each got.

#193 [13.0][IMP] storage_import_image_advanced: Add hook
  storage_import_image_advanced/models/import_image.py
Labels: approved, bot is merging ⏳, stale

#191 [15.0] [MIG] storage_image_product
  setup/storage_image_product/odoo/addons/storage_image_product
  setup/storage_image_product/setup.py
  storage_image_product/README.rst
  storage_image_product/__init__.py
  storage_image_product/__manifest__.py
  storage_image_product/i18n/storage_image_product.pot
  storage_image_product/models/__init__.py
  storage_image_product/models/category_image_relation.py
  storage_image_product/models/image_tag.py
  storage_image_product/models/product_category.py
  storage_image_product/models/product_image_relation.py
  storage_image_product/models/product_product.py
  storage_image_product/models/product_template.py
  storage_image_product/models/storage_image.py
  storage_image_product/readme/CONFIGURE.rst
  storage_image_product/readme/CONTRIBUTORS.rst
  storage_image_product/readme/DESCRIPTION.rst
  storage_image_product/readme/USAGE.rst
  storage_image_product/security/ir.model.access.csv
  storage_image_product/static/description/icon.png
  storage_image_product/static/description/index.html
  storage_image_product/tests/__init__.py
  storage_image_product/tests/common.py
  storage_image_product/tests/fixture/black-image.jpg
  storage_image_product/tests/fixture/logo-image.jpg
  storage_image_product/tests/fixture/white-image.jpg
  storage_image_product/tests/test_product_image_relation.py
  storage_image_product/views/image_tag.xml
  storage_image_product/views/product_category.xml
  storage_image_product/views/product_category_image_relation.xml
  storage_image_product/views/product_image_relation.xml
  storage_image_product/views/product_product.xml
  storage_image_product/views/product_template.xml
  storage_image_product/views/storage_image.xml
Labels: approved, ready to merge, bot is merging ⏳

#223 [14.0] Update pre-commit conf
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: needs review

#225 [13.0][UPD] copier template version
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  requirements.txt
  storage_file/README.rst
  storage_file/readme/CONTRIBUTORS.rst
  storage_file/readme/CREDITS.rst
  storage_file/readme/DESCRIPTION.rst
  storage_file/readme/ROADMAP.rst
Labels: bot is merging ⏳

#194 [13.0][IMP] storage_image_product: add navigation from image tag to products and categories
  storage_image_product/models/image_tag.py
  storage_image_product/views/image_tag.xml
Labels: approved, bot is merging ⏳, stale
