Repository OCA/storage, pull requests merged in 2022-05, with the labels that each got.

#182 [15.0][FIX] storage_backend_sftp: Fix paramiko usage
  storage_backend_sftp/components/sftp_adapter.py
Labels: bot is merging ⏳

#183 [14.0][FIX] storage_backend_sftp: Fix paramiko usage
  storage_backend_sftp/components/sftp_adapter.py
Labels: bot is merging ⏳

#173 [14.0] storage_image_product: ease main image lookup override
  storage_image_product/models/product_product.py
Labels: approved, ready to merge, bot is merging ⏳

#176 [13.0][IMP] storage_image_product: Limit attribute value selection according with available product attributes
  storage_image_product/models/product_image_relation.py
  storage_image_product/views/storage_image.xml
Labels: approved, ready to merge, bot is merging ⏳

#164 [14.0][IMP] storage_image_product: add missing index
  storage_image_product/models/category_image_relation.py
  storage_image_product/models/product_image_relation.py
Labels: approved, bot is merging ⏳

#154 storage_thumbnail: use internal URL on demand
  storage_file/models/storage_backend.py
  storage_file/models/storage_file.py
  storage_file/tests/test_storage_file.py
  storage_file/views/storage_backend_view.xml
  storage_image_product/models/product_template.py
  storage_thumbnail/models/thumbnail_mixin.py
  storage_thumbnail/tests/test_thumbnail.py
Labels: enhancement, approved, bot is merging ⏳
