Repository OCA/storage, pull requests merged in 2022-02, with the labels that each got.

#115 [13.0][IMP]storage_image_product: main image of the variant
  storage_image_product/models/product_product.py
  storage_image_product/tests/test_product_image_relation.py
Labels: approved, ready to merge, bot is merging ⏳

#168 [14.0][PORT] 115 from 13.0
  storage_image_product/models/product_product.py
  storage_image_product/tests/test_product_image_relation.py
Labels: needs review, bot is merging ⏳

#169 storage_file: refresh base url on startup
  storage_file/models/storage_backend.py
Labels: approved, bot is merging ⏳

#145 [15.0][MIG] storage_backend
  setup/storage_backend/odoo/addons/storage_backend
  setup/storage_backend/setup.py
  storage_backend/README.rst
  storage_backend/__init__.py
  storage_backend/__manifest__.py
  storage_backend/components/__init__.py
  storage_backend/components/base_adapter.py
  storage_backend/components/filesystem_adapter.py
  storage_backend/data/data.xml
  storage_backend/i18n/storage_backend.pot
  storage_backend/models/__init__.py
  storage_backend/models/storage_backend.py
  storage_backend/readme/CONTRIBUTORS.rst
  storage_backend/readme/DESCRIPTION.rst
  storage_backend/readme/HISTORY.rst
  storage_backend/readme/USAGE.rst
  storage_backend/security/ir.model.access.csv
  storage_backend/static/description/icon.png
  storage_backend/static/description/index.html
  storage_backend/tests/__init__.py
  storage_backend/tests/common.py
  storage_backend/tests/test_filesystem.py
  storage_backend/views/backend_storage_view.xml
Labels: approved, ready to merge, bot is merging ⏳
