Repository OCA/storage, pull requests merged in 2023-03, with the labels that each got.

#243 [13.0][FIX] storage_backend: avoid singleton error
  storage_backend/models/storage_backend.py
Labels: bot is merging ⏳

#246 [16.0][FIX] storage_backend: avoid singleton error
  storage_backend/models/storage_backend.py
Labels: bot is merging ⏳

#244 [14.0][FIX] storage_backend: avoid singleton error
  storage_backend/models/storage_backend.py
Labels: bot is merging ⏳

#248 [15.0] storage_backend_sftp: fix pin cryptography<37 + update pre-commit conf
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  requirements.txt
  storage_backend_sftp/__manifest__.py
Labels: needs review, bot is merging ⏳

#245 [15.0][FIX] storage_backend: avoid singleton error
  storage_backend/models/storage_backend.py
Labels: bot is merging ⏳

#180 [13.0][IMP] storage_backend_ftp: Implement Explicit FTP over TLS
  storage_backend_ftp/components/ftp_adapter.py
  storage_backend_ftp/models/storage_backend.py
Labels: approved, bot is merging ⏳, stale

#211 [14.0][IMP] storage_backend_ftp: Implement Explicit FTP over TLS
  storage_backend_ftp/components/ftp_adapter.py
  storage_backend_ftp/models/storage_backend.py
Labels: bot is merging ⏳, stale

#212 [15.0][IMP] storage_backend_ftp: Implement Explicit FTP over TLS
  storage_backend_ftp/components/ftp_adapter.py
  storage_backend_ftp/models/storage_backend.py
Labels: bot is merging ⏳, stale
