Repository OCA/storage, pull requests merged in 2023-10, with the labels that each got.

#282 [16.0] [FIX]multi_image/multi_media and thumbnail orders
  fs_file/README.rst
  fs_file/readme/HISTORY.rst
  fs_image_thumbnail/models/fs_image_thumbnail_mixin.py
  fs_image_thumbnail/readme/newsfragments/.gitignore
  fs_image_thumbnail/readme/newsfragments/282.bugfix
  fs_product_multi_image/models/product_product.py
  fs_product_multi_image/readme/newsfragments/.gitignore
  fs_product_multi_image/readme/newsfragments/282.bugfix
  fs_product_multi_image/tests/test_fs_product_multi_image.py
  fs_product_multi_media/models/product_product.py
  fs_product_multi_media/readme/newsfragments/.gitignore
  fs_product_multi_media/readme/newsfragments/282.bugfix
  fs_product_multi_media/tests/test_fs_product_multi_media.py
Labels: bot is merging ⏳

#268 storage_thumbnail: add method get_existing_thumbnail
  storage_thumbnail/models/thumbnail_mixin.py
Labels: bot is merging ⏳

#204 [15.0] [MIG] storage_media
  setup/storage_media/odoo/addons/storage_media
  setup/storage_media/setup.py
  storage_media/README.rst
  storage_media/__init__.py
  storage_media/__manifest__.py
  storage_media/data/ir_parameter.xml
  storage_media/i18n/storage_media.pot
  storage_media/models/__init__.py
  storage_media/models/storage_file.py
  storage_media/models/storage_media.py
  storage_media/models/storage_media_type.py
  storage_media/security/ir.model.access.csv
  storage_media/security/ir_rule.xml
  storage_media/security/res_group.xml
  storage_media/static/description/icon.png
  storage_media/tests/__init__.py
  storage_media/tests/test_storage_media.py
  storage_media/views/storage_media_view.xml
Labels: bot is merging ⏳, no stale

#227 [14.0][IMP] storage_image_product: add navigation from image tag to products (forward port)
  storage_image_product/models/image_tag.py
  storage_image_product/views/image_tag.xml
Labels: bot is merging ⏳, no stale

#228 [15.0][IMP] storage_image_product: add navigation from image tag to products (forward port)
  storage_image_product/models/image_tag.py
  storage_image_product/views/image_tag.xml
Labels: bot is merging ⏳, no stale

#258 [15.0][IMP] storage_backend: forward ports
  storage_backend/components/filesystem_adapter.py
  storage_backend/tests/common.py
  storage_backend/tests/test_filesystem.py
Labels: bot is merging ⏳, stale

#284 [16.0][FIX] fs_file: mimetype property computation on FSFileValue
  fs_file/fields.py
  fs_file/readme/CONTRIBUTORS.rst
  fs_file/readme/newsfragments/284.bugfix
  fs_file/tests/test_fs_file.py
Labels: bot is merging ⏳

#286 [16.0][FIX] fs_attachment: No db rules for storages not used as default for…
  fs_attachment/models/fs_storage.py
  fs_attachment/models/ir_attachment.py
  fs_attachment/readme/CONTRIBUTORS.rst
  fs_attachment/readme/newsfragments/.gitignore
  fs_attachment/readme/newsfragments/285.bugfix
  fs_attachment/readme/newsfragments/286.bugfix
  fs_storage/models/fs_storage.py
  fs_storage/readme/newsfragments/.gitignore
  fs_storage/readme/newsfragments/285.bugfix
Labels: approved, bot is merging ⏳

#288 [FIX] fs_file: Browse attachment with sudo to avoid read access errors
  fs_file/fields.py
  fs_file/readme/newsfragments/288.bugfix
Labels: bot is merging ⏳

#289 [FIX] Missing sudo for technical models. Basic users not able to add attachments
  fs_attachment/models/fs_storage.py
  fs_attachment/readme/newsfragments/289.bugfix
  fs_attachment/tests/test_fs_attachment.py
  fs_storage/models/fs_storage.py
  fs_storage/readme/newsfragments/289.bugfix
Labels: approved, bot is merging ⏳

#239 [ADD] attachment_db_by_checksum
  attachment_db_by_checksum/README.rst
  attachment_db_by_checksum/__init__.py
  attachment_db_by_checksum/__manifest__.py
  attachment_db_by_checksum/models/__init__.py
  attachment_db_by_checksum/models/ir_attachment.py
  attachment_db_by_checksum/models/ir_attachment_content.py
  attachment_db_by_checksum/readme/CONFIGURE.rst
  attachment_db_by_checksum/readme/CONTRIBUTORS.rst
  attachment_db_by_checksum/readme/DESCRIPTION.rst
  attachment_db_by_checksum/security/ir.model.access.csv
  attachment_db_by_checksum/static/description/index.html
  attachment_db_by_checksum/tests/__init__.py
  attachment_db_by_checksum/tests/test_attachment_by_checksum.py
  setup/attachment_db_by_checksum/odoo/addons/attachment_db_by_checksum
  setup/attachment_db_by_checksum/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#298 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  storage_backend/i18n/storage_backend.pot
  storage_backend/views/backend_storage_view.xml
  storage_file/i18n/storage_file.pot
  storage_file/views/storage_file_view.xml
  storage_image/i18n/storage_image.pot
  storage_image/views/storage_image.xml
  storage_image_product/i18n/storage_image_product.pot
  storage_image_product/views/image_tag.xml
  storage_import_image_advanced/i18n/storage_import_image_advanced.pot
  storage_import_image_advanced/views/import_product_image_view.xml
  storage_media/i18n/storage_media.pot
  storage_media/views/storage_media_view.xml
  storage_media_product/i18n/storage_media_product.pot
  storage_media_product/views/product.xml
  storage_thumbnail/i18n/storage_thumbnail.pot
  storage_thumbnail/views/storage_thumbnail_view.xml
Labels: help wanted, needs review, bot is merging ⏳
