Repository OCA/storage, pull requests merged in 2023-06, with the labels that each got.

#237 [13.0][FIX] storage_image_product: take available attributes from the line value_ids
  storage_image_product/models/product_template_attribute_line.py
Labels: approved, bot is merging ⏳, stale

#264 [14.0][FW] storage_image_product: #174 + #237
  storage_image_product/__manifest__.py
  storage_image_product/migrations/14.0.3.5.0/pre-migration.py
  storage_image_product/models/__init__.py
  storage_image_product/models/product_template_attribute_line.py
  storage_image_product/tests/test_product_image_relation.py
Labels: approved, bot is merging ⏳

#265 [15.0][FW] storage_image_product: #174 + #237
  storage_image_product/__manifest__.py
  storage_image_product/migrations/15.0.1.1.0/pre-migration.py
  storage_image_product/models/__init__.py
  storage_image_product/models/product_template_attribute_line.py
  storage_image_product/tests/test_product_image_relation.py
Labels: approved, bot is merging ⏳

#263 [FIX] storage_file: fix copy
  storage_file/models/storage_file.py
Labels: approved, ready to merge, bot is merging ⏳
