Repository OCA/storage, pull requests merged in 2024-05, with the labels that each got.

#368 [17.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .ruff.toml
  fs_attachment/models/ir_attachment.py
  fs_image/fields.py
Labels: help wanted, needs review, bot is merging ⏳

#369 [17.0][MIG] fs_base_multi_image + fs_product_multi_image: Migration to 17.0
  fs_base_multi_image/README.rst
  fs_base_multi_image/__init__.py
  fs_base_multi_image/__manifest__.py
  fs_base_multi_image/i18n/es.po
  fs_base_multi_image/i18n/fr.po
  fs_base_multi_image/i18n/fs_base_multi_image.pot
  fs_base_multi_image/i18n/it.po
  fs_base_multi_image/models/__init__.py
  fs_base_multi_image/models/fs_image.py
  fs_base_multi_image/models/fs_image_relation_mixin.py
  fs_base_multi_image/pyproject.toml
  fs_base_multi_image/readme/CONTRIBUTORS.md
  fs_base_multi_image/readme/DESCRIPTION.md
  fs_base_multi_image/readme/ROADMAP.md
  fs_base_multi_image/readme/USAGE.md
  fs_base_multi_image/security/fs_image.xml
  fs_base_multi_image/security/res_groups.xml
  fs_base_multi_image/static/description/icon.png
  fs_base_multi_image/static/description/index.html
  fs_base_multi_image/static/src/fields/fs_image_relation_dnd_upload/fs_image_relation_dnd_upload.esm.js
  fs_base_multi_image/static/src/fields/fs_image_relation_dnd_upload/fs_image_relation_dnd_upload.scss
  fs_base_multi_image/static/src/fields/fs_image_relation_dnd_upload/fs_image_relation_dnd_upload.xml
  fs_base_multi_image/views/fs_image.xml
  fs_base_multi_image/views/fs_image_relation_mixin.xml
  fs_product_multi_image/README.rst
  fs_product_multi_image/__init__.py
  fs_product_multi_image/__manifest__.py
  fs_product_multi_image/i18n/es.po
  fs_product_multi_image/i18n/fr.po
  fs_product_multi_image/i18n/fs_product_multi_image.pot
  fs_product_multi_image/i18n/it.po
  fs_product_multi_image/models/__init__.py
  fs_product_multi_image/models/fs_product_category_image.py
  fs_product_multi_image/models/fs_product_image.py
  fs_product_multi_image/models/image_tag.py
  fs_product_multi_image/models/product_category.py
  fs_product_multi_image/models/product_product.py
  fs_product_multi_image/models/product_template.py
  fs_product_multi_image/models/product_template_attribute_line.py
  fs_product_multi_image/pyproject.toml
  fs_product_multi_image/readme/CONTRIBUTORS.md
  fs_product_multi_image/readme/DESCRIPTION.md
  fs_product_multi_image/readme/HISTORY.md
  fs_product_multi_image/readme/USAGE.md
  fs_product_multi_image/readme/newsfragments/.gitignore
  fs_product_multi_image/security/fs_product_category_image.xml
  fs_product_multi_image/security/fs_product_image.xml
  fs_product_multi_image/static/description/icon.png
  fs_product_multi_image/static/description/index.html
  fs_product_multi_image/tests/__init__.py
  fs_product_multi_image/tests/test_fs_product_multi_image.py
  fs_product_multi_image/views/fs_product_category_image.xml
  fs_product_multi_image/views/fs_product_image.xml
  fs_product_multi_image/views/image_tag.xml
  fs_product_multi_image/views/product_category.xml
  fs_product_multi_image/views/product_product.xml
  fs_product_multi_image/views/product_template.xml
Labels: bot is merging ⏳

#353 [17.0][MIG] fs_product_brand_multi_image: Migration to 17.0
  fs_product_brand_multi_image/README.rst
  fs_product_brand_multi_image/__init__.py
  fs_product_brand_multi_image/__manifest__.py
  fs_product_brand_multi_image/i18n/es.po
  fs_product_brand_multi_image/i18n/fs_product_brand_multi_image.pot
  fs_product_brand_multi_image/i18n/it.po
  fs_product_brand_multi_image/models/__init__.py
  fs_product_brand_multi_image/models/fs_product_brand_image.py
  fs_product_brand_multi_image/models/image_tag.py
  fs_product_brand_multi_image/models/product_brand.py
  fs_product_brand_multi_image/pyproject.toml
  fs_product_brand_multi_image/readme/CONTRIBUTORS.md
  fs_product_brand_multi_image/readme/DESCRIPTION.md
  fs_product_brand_multi_image/readme/USAGE.md
  fs_product_brand_multi_image/security/fs_product_brand_image.xml
  fs_product_brand_multi_image/static/description/icon.png
  fs_product_brand_multi_image/static/description/index.html
  fs_product_brand_multi_image/views/fs_product_brand_image.xml
  fs_product_brand_multi_image/views/product_brand.xml
Labels: help wanted, needs fixing, approved, ready to merge, bot is merging ⏳

#365 [16.0][FIX] fs_attachment: respect controller parameters for /web/content/
  fs_attachment/models/ir_binary.py
  fs_attachment/tests/test_stream.py
Labels: bot is merging ⏳

#366 [16.0][FIX] fs_attachment: Rename file in storage when name is written
  fs_attachment/models/ir_attachment.py
  fs_attachment/tests/test_fs_attachment.py
Labels: bot is merging ⏳

#361 [16.0][IMP] fs_attachment: No crash on missing file
  fs_attachment/models/ir_attachment.py
  fs_attachment/readme/newsfragments/361.bugfix
  fs_attachment/static/description/index.html
Labels: bot is merging ⏳

#332 [16.0][CHG] fs_base_multi_image: drag and drop fixes
  fs_base_multi_image/models/fs_image_relation_mixin.py
  fs_base_multi_image/static/src/fields/fs_image_relation_dnd_upload/fs_image_relation_dnd_upload.esm.js
  fs_base_multi_image/views/fs_image_relation_mixin.xml
  fs_product_multi_image/views/fs_product_image.xml
  fs_product_multi_image/views/product_template.xml
Labels: approved, ready to merge, bot is merging ⏳

#372 [16.0][FIX] fs_storage: Change make_path_posix() to only 1 argument
  fs_storage/__manifest__.py
  fs_storage/rooted_dir_file_system.py
  requirements.txt
Labels: approved, bot is merging ⏳

#373 [17.0][FIX] fs_storage: Change make_path_posix() to only 1 argument
  fs_storage/__manifest__.py
  fs_storage/rooted_dir_file_system.py
  requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#359 [14.0][IMP]storage_media_product: gray out inactive relations
  storage_media_product/models/product.py
  storage_media_product/views/product.xml
Labels: approved, ready to merge, bot is merging ⏳

#346 [17.0][MIG] fs_image_thumbnail: Migration to 17.0
  fs_image_thumbnail/README.rst
  fs_image_thumbnail/__init__.py
  fs_image_thumbnail/__manifest__.py
  fs_image_thumbnail/i18n/es.po
  fs_image_thumbnail/i18n/fs_image_thumbnail.pot
  fs_image_thumbnail/i18n/it.po
  fs_image_thumbnail/models/__init__.py
  fs_image_thumbnail/models/fs_image_thumbnail_mixin.py
  fs_image_thumbnail/models/fs_thumbnail.py
  fs_image_thumbnail/models/ir_attachment.py
  fs_image_thumbnail/pyproject.toml
  fs_image_thumbnail/readme/CONTEXT.md
  fs_image_thumbnail/readme/CONTRIBUTORS.md
  fs_image_thumbnail/readme/CREDITS.md
  fs_image_thumbnail/readme/DESCRIPTION.md
  fs_image_thumbnail/readme/HISTORY.md
  fs_image_thumbnail/readme/USAGE.md
  fs_image_thumbnail/readme/newsfragments/.gitignore
  fs_image_thumbnail/security/fs_thumbnail.xml
  fs_image_thumbnail/static/description/icon.png
  fs_image_thumbnail/static/description/index.html
  fs_image_thumbnail/tests/__init__.py
  fs_image_thumbnail/tests/test_fs_image_thumbnail.py
  fs_image_thumbnail/views/fs_image_thumbnail_mixin.xml
  fs_image_thumbnail/views/fs_thumbnail.xml
  fs_image_thumbnail/views/ir_attachment.xml
Labels: bot is merging ⏳
