Repository OCA/storage, pull requests merged in 2024-02, with the labels that each got.

#320 [16.0][IMP] fs_storage: invalidate filesystem cache when connection fails
  fs_storage/README.rst
  fs_storage/models/fs_storage.py
  fs_storage/readme/USAGE.rst
  fs_storage/readme/newsfragments/320.feature
  fs_storage/static/description/index.html
Labels: approved, bot is merging ⏳

#241 [16.0][MIG] storage_backend_sftp: Migration to 16.0
  requirements.txt
  setup/storage_backend_sftp/odoo/addons/storage_backend_sftp
  setup/storage_backend_sftp/setup.py
  storage_backend_sftp/README.rst
  storage_backend_sftp/__init__.py
  storage_backend_sftp/__manifest__.py
  storage_backend_sftp/components/__init__.py
  storage_backend_sftp/components/sftp_adapter.py
  storage_backend_sftp/i18n/storage_backend_sftp.pot
  storage_backend_sftp/models/__init__.py
  storage_backend_sftp/models/storage_backend.py
  storage_backend_sftp/static/description/icon.png
  storage_backend_sftp/tests/__init__.py
  storage_backend_sftp/tests/test_sftp.py
  storage_backend_sftp/views/backend_storage_view.xml
Labels: bot is merging ⏳, stale

#340 [FIX] delete FsImageThumbnail on attachment delete
  fs_image_thumbnail/models/fs_image_thumbnail_mixin.py
Labels: approved, bot is merging ⏳

#333 [16.0][FIX] fs_product_multi_image: fix kanban view image display
  fs_product_multi_image/views/fs_product_image.xml
Labels: bot is merging ⏳

#317 [16.0][IMP] fs_storage: pattern matching should only apply to file name, not full path
  fs_storage/models/fs_storage.py
Labels: bot is merging ⏳

#334 [IMP] fs_storage: use fs.info() to check for the marker file
  fs_storage/models/fs_storage.py
Labels: approved, bot is merging ⏳

#336 [16.0][FIX] fs_storage: fix test connection when __fs slot is not initialized
  fs_storage/models/fs_storage.py
Labels: approved, bot is merging ⏳

#339 [IMP] fs_attachment: more robust pre_init_hook
  fs_attachment/hooks.py
Labels: bot is merging ⏳

#341 [16.0][FIX] fs_file: Support for empty file
  fs_file/README.rst
  fs_file/fields.py
  fs_file/readme/newsfragments/341.bugfix
  fs_file/static/description/index.html
  fs_file/tests/test_fs_file.py
  fs_image/README.rst
  fs_image/readme/newsfragments/305.bugfix
  fs_image/static/description/index.html
Labels: bot is merging ⏳
