Repository OCA/storage, pull requests merged in 2024-11, with the labels that each got.

#412 [FIX] fs_attachment: remove unwanted args
  fs_attachment/README.rst
  fs_attachment/fs_stream.py
  fs_attachment/readme/CONTRIBUTORS.rst
  fs_attachment/static/description/index.html
Labels: bot is merging ⏳

#413 [17.0][FIX] fs_attachment: Add CSP header for fs stream
  fs_attachment/fs_stream.py
  fs_attachment/tests/test_stream.py
Labels: bot is merging ⏳

#416 [16.0] fs_attachment: Oca port from 17.0 to 16.0 pr 344 368 363 402 413
  .oca/oca-port/blacklist/fs_attachment.json
  fs_attachment/fs_stream.py
  fs_attachment/models/fs_storage.py
  fs_attachment/tests/test_stream.py
Labels: bot is merging ⏳

#415 [17.0][FIX] fs_attachment: remove unwanted args
  fs_attachment/README.rst
  fs_attachment/fs_stream.py
  fs_attachment/readme/CONTRIBUTORS.md
  fs_attachment/static/description/index.html
Labels: bot is merging ⏳

#414 [17.0][FIX] allow serving field attachment with fs stream
  fs_attachment/models/ir_binary.py
  fs_attachment/tests/test_stream.py
Labels: bot is merging ⏳

#406 [16.0][PW] storage_backend: Port from 14.0
  .oca/oca-port/blacklist/storage_backend.json
  storage_backend/components/filesystem_adapter.py
  storage_backend/models/storage_backend.py
  storage_backend/tests/common.py
  storage_backend/tests/test_filesystem.py
Labels: bot is merging ⏳

#407 [18.0][MIG] storage_backend: Migration to 18.0
  .oca/oca-port/blacklist/storage_backend.json
  storage_backend/README.rst
  storage_backend/__init__.py
  storage_backend/__manifest__.py
  storage_backend/components/__init__.py
  storage_backend/components/base_adapter.py
  storage_backend/components/filesystem_adapter.py
  storage_backend/data/data.xml
  storage_backend/i18n/es.po
  storage_backend/i18n/it.po
  storage_backend/i18n/storage_backend.pot
  storage_backend/models/__init__.py
  storage_backend/models/storage_backend.py
  storage_backend/pyproject.toml
  storage_backend/readme/CONTRIBUTORS.md
  storage_backend/readme/CREDITS.md
  storage_backend/readme/DESCRIPTION.md
  storage_backend/readme/HISTORY.md
  storage_backend/readme/USAGE.md
  storage_backend/security/ir.model.access.csv
  storage_backend/static/description/icon.png
  storage_backend/static/description/index.html
  storage_backend/tests/__init__.py
  storage_backend/tests/common.py
  storage_backend/tests/test_filesystem.py
  storage_backend/views/backend_storage_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#403 [18.0][MIG] fs_attachment: Migration to 18.0
  fs_attachment/README.rst
  fs_attachment/__init__.py
  fs_attachment/__manifest__.py
  fs_attachment/fs_stream.py
  fs_attachment/hooks.py
  fs_attachment/i18n/es.po
  fs_attachment/i18n/fr.po
  fs_attachment/i18n/fs_attachment.pot
  fs_attachment/i18n/it.po
  fs_attachment/i18n/zh_CN.po
  fs_attachment/models/__init__.py
  fs_attachment/models/fs_file_gc.py
  fs_attachment/models/fs_storage.py
  fs_attachment/models/ir_attachment.py
  fs_attachment/models/ir_binary.py
  fs_attachment/models/ir_model.py
  fs_attachment/models/ir_model_fields.py
  fs_attachment/models/strtobool.py
  fs_attachment/pyproject.toml
  fs_attachment/readme/CONTRIBUTORS.md
  fs_attachment/readme/DESCRIPTION.md
  fs_attachment/readme/HISTORY.md
  fs_attachment/readme/USAGE.md
  fs_attachment/readme/newsfragments/.gitignore
  fs_attachment/readme/newsfragments/361.bugfix
  fs_attachment/security/fs_file_gc.xml
  fs_attachment/static/description/icon.png
  fs_attachment/static/description/index.html
  fs_attachment/tests/__init__.py
  fs_attachment/tests/common.py
  fs_attachment/tests/test_fs_attachment.py
  fs_attachment/tests/test_fs_attachment_file_like_adapter.py
  fs_attachment/tests/test_fs_attachment_internal_url.py
  fs_attachment/tests/test_fs_storage.py
  fs_attachment/tests/test_stream.py
  fs_attachment/views/fs_storage.xml
  requirements.txt
Labels: approved, bot is merging ⏳

#419 [16.0][FIX] fs_attachment: allow serving field attachment with fs stream
  fs_attachment/models/ir_binary.py
  fs_attachment/tests/test_stream.py
Labels: bot is merging ⏳

#420 [18.0] fs_attachment Oca port from 17.0 to 18.0 pr 344 368 413 415 414
  .oca/oca-port/blacklist/fs_attachment.json
  fs_attachment/README.rst
  fs_attachment/fs_stream.py
  fs_attachment/models/ir_binary.py
  fs_attachment/readme/CONTRIBUTORS.md
  fs_attachment/static/description/index.html
  fs_attachment/tests/test_stream.py
Labels: bot is merging ⏳

#378 [17.0][IMP] fs_attachment: send the mimetype information for S3
  fs_attachment/models/ir_attachment.py
Labels: bot is merging ⏳

#422 [16.0][IMP] fs_attachment: send the mimetype information for S3
  fs_attachment/models/ir_attachment.py
Labels: bot is merging ⏳

#421 [18.0][IMP] fs_attachment: send the mimetype information for S3
  fs_attachment/models/ir_attachment.py
Labels: bot is merging ⏳

#377 [16.0][ADD] fs_product_public_category_multi_image: a drop-in replacement o…
  fs_product_public_category_multi_image/README.rst
  fs_product_public_category_multi_image/__init__.py
  fs_product_public_category_multi_image/__manifest__.py
  fs_product_public_category_multi_image/models/__init__.py
  fs_product_public_category_multi_image/models/fs_product_public_category_image.py
  fs_product_public_category_multi_image/models/image_tag.py
  fs_product_public_category_multi_image/models/product_public_category.py
  fs_product_public_category_multi_image/readme/CONTRIBUTORS.rst
  fs_product_public_category_multi_image/readme/DESCRIPTION.rst
  fs_product_public_category_multi_image/readme/USAGE.rst
  fs_product_public_category_multi_image/security/fs_product_public_category_image.xml
  fs_product_public_category_multi_image/static/description/icon.png
  fs_product_public_category_multi_image/static/description/index.html
  fs_product_public_category_multi_image/tests/__init__.py
  fs_product_public_category_multi_image/tests/test_fs_product_multi_image.py
  fs_product_public_category_multi_image/views/fs_product_public_category_image.xml
  fs_product_public_category_multi_image/views/product_public_category.xml
  setup/fs_product_public_category_multi_image/odoo/addons/fs_product_public_category_multi_image
  setup/fs_product_public_category_multi_image/setup.py
Labels: bot is merging ⏳, stale

#382 [17.0][IMP] fs_storage: Allow setting eval_options_from_env in configuration file
  fs_storage/models/fs_storage.py
Labels: bot is merging ⏳

#424 [18.0][IMP] fs_storage: Allow setting eval_options_from_env in configuration file
  fs_storage/models/fs_storage.py
Labels: bot is merging ⏳

#423 [16.0] fs_storage: Allow setting eval_options_from_env in configuration file
  .oca/oca-port/blacklist/fs_storage.json
  fs_storage/models/fs_storage.py
Labels: bot is merging ⏳

#426 [17.0] fs_attachement: fix fs_url computing
  .oca/oca-port/blacklist/fs_attachment.json
  fs_attachment/models/fs_storage.py
  fs_attachment/tests/test_fs_storage.py
Labels: bot is merging ⏳

#427 [18.0][FIX] fs_attachment: fix fs_url computing
  .oca/oca-port/blacklist/fs_attachment.json
  fs_attachment/models/fs_storage.py
  fs_attachment/tests/test_fs_storage.py
Labels: bot is merging ⏳

#429 [16.0][IMP] fs_image: Add download button
  fs_image/static/src/scss/fsimage_field.scss
  fs_image/static/src/views/fields/fsimage_field.esm.js
  fs_image/static/src/views/fields/fsimage_field.xml
Labels: bot is merging ⏳
