Repository OCA/storage, pull requests merged in 2024-10, with the labels that each got.

#396 [17.0][PORT] 355 from 16.0
  fs_storage/models/fs_storage.py
Labels: needs review, bot is merging ⏳

#397 [17.0][FW] fs_storage: forward port v16 changes
  fs_storage/__init__.py
  fs_storage/__manifest__.py
  fs_storage/models/fs_storage.py
  fs_storage/readme/USAGE.md
  fs_storage/readme/newsfragments/320.feature
  fs_storage/security/ir.model.access.csv
  fs_storage/views/fs_storage_view.xml
  fs_storage/wizards/__init__.py
  fs_storage/wizards/fs_test_connection.py
  fs_storage/wizards/fs_test_connection.xml
Labels: approved, bot is merging ⏳

#399 [MIG] fs_storage: Migration to 18.0
  fs_storage/README.rst
  fs_storage/__init__.py
  fs_storage/__manifest__.py
  fs_storage/demo/fs_storage_demo.xml
  fs_storage/i18n/es.po
  fs_storage/i18n/fs_storage.pot
  fs_storage/i18n/it.po
  fs_storage/i18n/storage_backend.pot
  fs_storage/i18n/zh_CN.po
  fs_storage/models/__init__.py
  fs_storage/models/fs_storage.py
  fs_storage/odoo_file_system.py
  fs_storage/pyproject.toml
  fs_storage/readme/CONTRIBUTORS.md
  fs_storage/readme/DESCRIPTION.md
  fs_storage/readme/HISTORY.md
  fs_storage/readme/ROADMAP.md
  fs_storage/readme/USAGE.md
  fs_storage/readme/newsfragments/.gitignore
  fs_storage/readme/newsfragments/320.feature
  fs_storage/rooted_dir_file_system.py
  fs_storage/security/ir.model.access.csv
  fs_storage/static/description/icon.png
  fs_storage/static/description/index.html
  fs_storage/tests/__init__.py
  fs_storage/tests/common.py
  fs_storage/tests/test_fs_storage.py
  fs_storage/views/fs_storage_view.xml
  fs_storage/wizards/__init__.py
  fs_storage/wizards/fs_test_connection.py
  fs_storage/wizards/fs_test_connection.xml
  requirements.txt
Labels: bot is merging ⏳

#409 [17.0][FWP] fs_base_multi_image: drag and drop fixes
  fs_base_multi_image/models/fs_image_relation_mixin.py
  fs_base_multi_image/static/src/fields/fs_image_relation_dnd_upload/fs_image_relation_dnd_upload.esm.js
  fs_base_multi_image/views/fs_image_relation_mixin.xml
  fs_product_multi_image/views/fs_product_image.xml
  fs_product_multi_image/views/product_template.xml
Labels: bot is merging ⏳
