Repository OCA/storage, pull requests merged in 2024-07, with the labels that each got.

#380 [FIX] fs_product_multi_image/fs_file_demo: Avoid warnings for duplicate fields labels
  fs_file_demo/models/fs_file.py
  fs_product_multi_image/models/product_product.py
  fs_product_multi_image/models/product_template.py
Labels: bot is merging ⏳

#383 [14.0][FIX] storage_thumbnail: always use slugified url_key
  storage_thumbnail/models/thumbnail_mixin.py
  storage_thumbnail/tests/test_thumbnail.py
Labels: approved, bot is merging ⏳

#385 [16.0][FIX] fs_storage: add missing sudo when creating FilsSystem
  fs_storage/models/fs_storage.py
Labels: approved, bot is merging ⏳

#273 [14.0][IMP] storage_image: Add a wizard to replace related file
  storage_file/__init__.py
  storage_file/wizards/__init__.py
  storage_file/wizards/replace_file.py
  storage_image/__init__.py
  storage_image/__manifest__.py
  storage_image/security/ir.model.access.csv
  storage_image/tests/__init__.py
  storage_image/tests/static/oca.png
  storage_image/tests/test_storage_replace_file.py
  storage_image/views/storage_image.xml
  storage_image/wizards/__init__.py
  storage_image/wizards/replace_file.py
  storage_image/wizards/replace_file.xml
  storage_media/__init__.py
  storage_media/__manifest__.py
  storage_media/tests/__init__.py
  storage_media/tests/test_storage_replace_file.py
  storage_media/views/storage_media_view.xml
  storage_media/wizards/__init__.py
  storage_media/wizards/replace_file.py
  storage_media/wizards/replace_file.xml
Labels: approved, bot is merging ⏳

#381 [16.0][CHG] fs_product_multi_image: fs.product.category.image views
  fs_product_multi_image/views/fs_product_category_image.xml
  fs_product_multi_image/views/product_category.xml
Labels: bot is merging ⏳

#386 [16.0][FIX] fs_attachment: Prevent recompute_urls from skipping records with res_field != False
  fs_attachment/models/fs_storage.py
  fs_attachment/tests/test_fs_storage.py
Labels: approved, ready to merge, bot is merging ⏳
