Repository OCA/storage, pull requests merged in 2025-03, with the labels that each got.

#457 [FIX] fs_storage: Add a KeyError Exception
  fs_storage/models/fs_storage.py
Labels: approved, bot is merging ⏳

#458 [17.0][FIX] fs_storage: Add a generic Exception
  fs_storage/models/fs_storage.py
Labels: bot is merging ⏳

#459 [18.0][FIX] fs_storage: Add a generic Exception
  fs_storage/models/fs_storage.py
Labels: bot is merging ⏳

#453 [18.0][FIX] fs_storage: fix `_ls_check_connection` when dealing with huge amount of files in root folder
  fs_storage/models/fs_storage.py
Labels: approved, bot is merging ⏳

#435 [18.0][MIG] storage_thumbnail: Migration to 18.0
  .oca/oca-port/blacklist/storage_thumbnail.json
  storage_thumbnail/README.rst
  storage_thumbnail/__init__.py
  storage_thumbnail/__manifest__.py
  storage_thumbnail/data/ir_parameter.xml
  storage_thumbnail/i18n/storage_thumbnail.pot
  storage_thumbnail/models/__init__.py
  storage_thumbnail/models/storage_file.py
  storage_thumbnail/models/storage_thumbnail.py
  storage_thumbnail/models/thumbnail_mixin.py
  storage_thumbnail/pyproject.toml
  storage_thumbnail/readme/CONTRIBUTORS.md
  storage_thumbnail/readme/CREDITS.md
  storage_thumbnail/readme/DESCRIPTION.md
  storage_thumbnail/security/ir.model.access.csv
  storage_thumbnail/static/description/icon.png
  storage_thumbnail/static/description/index.html
  storage_thumbnail/tests/__init__.py
  storage_thumbnail/tests/models.py
  storage_thumbnail/tests/static/akretion-logo.png
  storage_thumbnail/tests/test_thumbnail.py
  storage_thumbnail/views/storage_thumbnail_view.xml
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#460 [18.0][IMP] fs_attachement, fs_storage: Move storage to model / field association to base addon
  fs_attachment/models/__init__.py
  fs_attachment/models/fs_storage.py
  fs_attachment/tests/test_fs_storage.py
  fs_attachment/views/fs_storage.xml
  fs_storage/README.rst
  fs_storage/models/__init__.py
  fs_storage/models/fs_storage.py
  fs_storage/models/ir_model.py
  fs_storage/models/ir_model_fields.py
  fs_storage/readme/CONTRIBUTORS.md
  fs_storage/static/description/index.html
  fs_storage/tests/test_fs_storage.py
  fs_storage/views/fs_storage_view.xml
Labels: approved, ready to merge, bot is merging ⏳
