Repository OCA/storage, pull requests merged in 2025-07, with the labels that each got.

#490 [17.0][FIX] fs_attachment: domain to store attachment in db was always [(1 '=', 1)]
  .oca/oca-port/blacklist/fs_attachment.json
  fs_attachment/models/ir_attachment.py
  fs_attachment/tests/test_fs_attachment.py
Labels: bot is merging ⏳

#491 [16.0][FIX] fs_attachment: domain to store attachment in db was always [(1, '=', 1)]
  fs_attachment/models/ir_attachment.py
  fs_attachment/tests/test_fs_attachment.py
Labels: bot is merging ⏳

#494 [16.0] [BKP] fs_storage: add helper method
  fs_attachment/models/ir_attachment.py
  fs_storage/models/fs_storage.py
Labels: bot is merging ⏳

#495 [17.0] [BKP] fs_storage: add helper method
  fs_attachment/models/ir_attachment.py
  fs_storage/models/fs_storage.py
Labels: bot is merging ⏳

#485 [18.0][IMP] fs_storage: Allow setting check_connection_method in configuration file
  fs_storage/models/fs_storage.py
  fs_storage/readme/newsfragments/+allow_setting_check_connection_method_server_env.feature
  fs_storage/upgrades/18.0.2.1.0/post-update.py
Labels: approved, ready to merge, bot is merging ⏳

#493 [18.0] storage_backend_s3: make regions static
  storage_backend_s3/models/storage_backend.py
  storage_backend_s3/regions.py
Labels: bot is merging ⏳

#492 [18.0] make force_storage_to_db_for_special_fields more flexible
  fs_attachment/models/ir_attachment.py
Labels: approved, bot is merging ⏳

#498 [16.0][FW] [18.0] make force_storage_to_db_for_special_fields more flexible
  fs_attachment/models/ir_attachment.py
Labels: bot is merging ⏳

#499 [17.0][FW] [18.0] make force_storage_to_db_for_special_fields more flexible
  fs_attachment/models/ir_attachment.py
Labels: bot is merging ⏳
